services:
  typesense:
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    env_file:
      - .env
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors'

  api:
    build: .
    restart: on-failure
    ports:
      - "8100:8100"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - typesense
    environment:
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_PROTOCOL=http


  qdrant:
    image: qdrant/qdrant
    restart: on-failure
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z