services:
  typesense:
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    env_file:
      - .env
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors'